#+OPTIONS: num:nil H:2 toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:t tags:not-in-toc
#+TITLE: How to Make Money in Stocks 


* Overview
How to Make Money in Stocks: A Winning System in Good Times and Bad by
William O'Neil 

* CAN SLIM
+ C 当季每股收益。至少应该上涨18％－20％，并且越高越好。同时，当季销售量应该增加至少25％。 
+ A 年度每股收益增长率。在过去3年内应该保持显著的增长率，同时股本收益率保持在17％以上。 
+ N 新公司,新产品,新管理阶层,股价新高: 选择正确时机买入.
+ S 供给和需求。在外流通的股份加巨大的需求。 
+ L 领军股或拖油瓶
+ I 专业机构投资者的认同度:关注主力机构方向
+ M 市场走向。学会读解大盘的每日股价和我成交量变化和领先的个人投资者的
  行动来判断市场的总体走势。这决定你是输是赢。
* 学会识图
+ 历史总会重复:学会以史为鉴
+ 最普遍的价格形态:带柄茶杯形态
+ 价格形态形成阶段包含窄幅波动区间
+ 找到中轴点并关注"成交量变化幅度"
+ 在接近价格形态的低点出寻找成交量萎缩的时点
+ 大额成交量的信号很有价值
+ 一些典型的带柄茶杯价格形态
+ 市场调整的价值
** 其他价格形态
+ 如何发现"带柄茶碟形"价格形态
+ 认识"双重底"价格形态
+ "平底"价格形态的定义
+ "方盒子"的新形态
+ 罕见的高而窄旗形形态
+ 何谓"双重价格形态"
+ 盘升的价格形态
+ 宽松的价格结构容易导致失败
+ 什么是保值型供给
+ 在新股中寻觅绝佳机会

* C
Earnings Per Share (EPS)

+ 寻找当期收益大幅增长的股票
+ 警惕收益报表的误导
+ 忽略昙花一现的巨额盈利
+ 设定当期每股收益增幅的最低标准
+ 回避那些安于现状的老牌大公司
+ 寻找每季收益加速增长的公司
+ 寻找销售额和每股收益同步增长的股票
+ 警惕连续两个季度的收益大幅回落
+ 研究对数坐标周线图
+ 对比分析行业中的其他股票

筛选适合投资的股票,其当季每股收益需要同比大幅度提高至少25%~50%.如果想
要优中选优,其每股收益增幅需要高达100%~500%甚至更高.

* A
+ 选择年度收益增长率至少为25%~50%的股票
+ 寻找股本回报率高的股票
  return on equity, ROE
+ 检验公司过往3年的收益稳定性
+ 年度收益和当季收益都应该出类拔萃
+ 市盈率真的如此重要吗
+ 分析同一行业公司的误区
+ 不要做空高市盈率的股票

应该关注这样的股票:在过去3年中,每年的收益增长都很显著,而且近期的季度收
益有大幅的提升.切记:这是选股的最低标准.

* N
+ 引领股价大涨的新产品

归纳而言,应该选择这样的公司,开发了重要的新产品或服务,或者从新管理层,抑
或是大为改善的产业环境中获益匪浅.然后,如果这些股票从有效的价格调整形态
中突破出来,而且交易量增加,并接近或已经创下价格新高,就要果断买入.
* S
+ 股票供给量的大小
+ 看重管理层的创业精神
+ 过度分拆股票可能会有不利影响
+ 关注那些在公开市场中进行回购的公司
+ 负债率低的公司往往较好
+ 评估供给与需求情况
只要应用CAN SLIM体系,任何规模市值的股票都可以买入.但低市值股票无论上涨
还是下跌,波动都更剧烈.有时,市场的重心会从低市值股票转为高市值股票,反之
亦然.我们更为推荐在公开市场进行回购以及管理层持股比例可观的公司.
* L
+ 优中选优方可买入
+ 切忌东施效
+ 如何区分领军股和滞后股:使用股价相对强度
+ 在市场调整阶段寻找新的领军股
+ 在弱势市场中寻找强势股票

即使看似便宜,投资于滞后股也很少能给你带来回报,必须寻找并且将你的选股范
围限定为市场领军股.一旦股价低于买入价的8%,赶紧卖出那些滞后的"失败者",
以免因冒险让自己伤得更深.

* I
+ 分析机构投资者的数量和质量
+ 买进机构认同度在上升的股票
+ 关注机构投资者本季度购进的股票
+ 被机构投资者过量持有吗
+ "别在成长股高峰买入"是不容辩驳的操作原理
+ 机构认同度意味着市场流动性

至少被几家业绩水平优于行业平均水平的机构投资者持有,并且近几个季度内机
构投资者数量有所增加.

* M
+ 股市市场周期的阶段
+ 应该每日研究主要大盘指数
+ 长期投资与充分投入的荒诞
+ 在市场低迷时学会保护自己
+ 运用止损指令
+ 跟踪分析大盘首次回落后每一次的反弹企图
+ 第一次反弹可能失败的三种标志
  如果出现下面几种情况,你也就可能判断这是一次非常无力的反弹:(1) 指数在
  第三天,第四天,第五天里上涨,但是成交量却在下降;(2)大盘指数几乎不会比
  前一日表现好;(3) 大盘指数的反弹没有达到跌幅的50%以上.
+ 紧跟领军股探寻大盘顶点
+ 不要过早重返股市, 所有的牛市开始都是伴随着强烈的价格和成交量上涨而展
  开反弹的,等待和观察大盘表现绝对是值得的.
+ 大赚特赚还看牛头
+ 解读被高估的涨跌线指标
+ 关注联邦储备委员会的相关利率变化情况: 联邦储备贴现率(Federal reserve
  board's discount rate,美联储向其他成员银行收取的贷款利率),联邦资金利
  率(Fed funds rate,有资金储备的银行向无资金储备的银行收取的贷款利率)
  与股票保证金水平是值得关注的指标.

关键不在于可以预测或知道市场将做什么,而是要知道并懂得市场在过去的几周
中发生了什么变化,而它当前又在如何演化.

* 抛售止损策略
在股市中取得巨大成功的首要秘诀并非在任何时刻都是正确的，而是在错误的时候能让
损失额降低到最低水平。 
** 何谓真正的损失
到底卖不卖,还有一个建议可以帮助你做决定： 

假使你并不拥有这支股票，拥有的是存在银行的市值相同的钱，再问问自己:现
在真的想买这支股票吗? 

** 毫无例外的将损失控制在成本的7%或8%
Bill Astrop认为,个人投资者在股价低于买入价5%时就应该抛出一半股票,而低
于10%时则应全部抛掉.
** 所有普通股都有风险和投机性
** 止损正如买保险
** 迅速止损,缓慢收利
** 应该摊低股票的成本吗
市场上只有两种心情：期盼和担心。唯一的问题是，当我们应该担心的时候却在
期盼，当我们应该期盼的时候却在担心。 
* 卖出获利策略
** 必须制定损益方案
1960年制定的买入规则:
1. 集中注意那些股价超过20美元,并至少受到一些机构投资者认同的上市股票.
2. 所要投资公司的每股收益必须在过去5年中每年都有所增长,而且其当季收益
   至少上涨了20%.
3. 当某只股票突破了合理的调整以及价格巩固阶段后,正在或将要创下价格新高
   时,应该迅速买入.与此同时,日成交量应该比该股票的平均水平至少增加50%.
** 修正后的损益方案

如果某支股票在8周以内涨升20％，至少要持有该股票到8周以上。然后，再研究
该股票是否值得再持有6个月，以享受长期资本利得课税优惠(当时美国以6个月
作为长短资本利得的分界线)。如果股票跌落到成本以下8％ ,就止损退场。修正
之后的利损计划是这样的：赚20%时出场(除超强股以外)，从买人价下跌8%时止
损。

最初买入的股票上涨2%或2.5%时就迅速进行第一次跟进.这就降低了因为犹豫不
决而导致股价上涨5%-10%时才进行买进的几率.

** 卖出股票时应牢记亮点
首先，选择正确的股票能够为成功卖出奠定一大半的基础。如果刚开始就在适当
时机买进一支刚自调整价格形态向上突破的股票，而且在不超过高于买点5%的价
位加码进筹，你将可以不受日后股价修正的影响。赚钱的股票很少会跌落到正确
买点的8％以下。实际上，很多非常赚钱的股票根本就不会低于其止确买点。所
以说，在正确买点买入股票绝对非常必要，这也可能会让你更快地将小部分亏损
幅度还未及8％的股票进行止损。也许在一支股票还未下跌到4％至5 ％时，你就
已经知道这个选择是错的。 

其次，在牛市行情里买入一支股票后，注意那些出现的大卖单。这些大卖单
可能是短暂、不一致地出现，而且和以往的成交量相比也不算太大。但最强的股
票此时可能出现为时一周或数周较强的卖压。要用全面的观点来分析股市行情，
以免被正常的股价拉回吓倒或退场。 

** 卖出股票的技术性征兆
要想知道某支股票是否到达最高点，可以参照很多不同的迹象表现。其中包括价
格在一高点处徘徊、交易量下降和其他虚弱的迹象。如果你进一步研究这些信息，
每天做决策时将它们考虑在内，其中很多信息就会变得更加明朗。

** 顶峰前最后的疯狂
1. 当日价格涨升最多的那一天。如果某支股票的价格在好几个月里都向上推升
   (和买入点相比，股价从合理和适当的价格形态明显上扬)，在某天的收盘价
   比开始上扬后任何天内涨升的幅度都要大得多，注意！通常这就非常接近顶
   峰和最高点了。 
2. 最大的日成交量。股价的最高点可能出现于该只股票开始上涨以来成交量最
   大的那一天.
3. 消耗型缺口。如果某支股票在构筑了好儿个月的价格形态之后快速涨升，从
   而和前一天的价格之间形成一个缺口，那么该涨升也就接近顶点了。 
4. 顶峰前最后的疯狂表现.如果某一股票近期涨势过于强劲,比如在周线图中已
   有连续两三周的迅速上涨,或是在日线图上,连续8-10天中有7-8天强劲上扬,
   赶紧将其抛出.这被称为顶峰前最后的疯狂,此时,股票当周的高低价差几乎总
   是比多个月前涨势开始之后的每一周价差都要高,虽然成交规模仍然很大,但
   当日的收盘价仅有小幅上涨.我把这一现象称为"铁路轨道",因为你会在周线
   图上看到两根垂直的平行线.这一迹象说明,尽管成交量持续上涨,但当周的股
   价却没有什么明显提升.
5. 出货行为的信号.长期上涨后,伴随着巨额成交量,股价却毫无起色,这一迹象
   表明市场出现了出货行为.在那些对市场仍然抱有鉴定信心的买家收到强烈冲
   击之前,赶紧将股票卖出.你还应该清楚,聪明的投资者何时应该取得长期的资
   本收益.
6. 股票分拆。如果由于股票分割而使其股价在1周或2周内涨升20％到25％，那
   就卖掉它。过多地将股票进行分割往往代表着股价已接近最高点。如果某股
   价从其价格形态向上突破后，公司宣布要进行股票分割，大多数情况下应该
   出清该股票了。 
7. 连续下跌的天数增加。股价连续走低而非上扬的日子可能会发生变化，在大
   多数股票开始从顶点下落之后却又涨升。你可能会发现在经历4至5天的下降
   后，股价又上涨了2至3天，尽管之前你所见到的是股价上扬4天后又下跌2至3
   天。 
8. 上升轨道线。在某些情况下，如果某股票经历了大幅度涨升后到达其上升轨
   道线，即应卖掉(在股价图上，轨道线指的由数月内最低股价之间的连线以及
   最高股价之间的连线得出的两条平行线)。分析显示当股票快速涨至上升轨道
   线时，应出清该股.
9. 200天移动平均线。当股价超过其200天平均移动线价格水平之上70％到80％
   时则可以进行卖出,但我几乎从未这么样做过。 
10. 股票从最高点跌落后应出清。当股票还在涨升时你没有卖掉它，就应该当其
    从最高点跌落时卖掉。在初次股价崩滑后，某些股票还有可能在某次重新攀
    回。 

** 成交量萎缩以及其他一些市场疲软的表现
1. 低成交量情况下股价达到新高。有的股票在较低或较差的成交量基础上还能
   创下新高。随着股价涨升，成交量则越来越低，这表明大户已经失去了对该
   股票的兴趣。 
2. 收盘价接近于当天的最低价.从每日股价图上我们根据向下“箭头”的指
   示看出最高点所在。也就是，股票会连续好几天地接近或到达当日的最低点，
   将当日上涨的幅度完全消化掉。 
3. 第三阶段或是第四阶段价格形态.当股票突破第三或是第四阶段价格形态后创
   下股价新高时将其卖出.市场对于某一股票的第三次上扬已经基本没有什么兴
   趣了.因为这时,该股票的上升趋势已经过于明显,几乎每一个人都注意到了.而
   且,这些后期的价格形态通常都是有缺陷的,看起来过于宽松.第四阶段价格形
   态的失败率更是达到了80%,但前提是你必须能够确定该股票处于第四阶段价
   格形态.
4. 股价弱势反弹的表现。当你在最高点附近看到第一次大量股票出售时，下一
   次的成交量即使回升，其回升量也萎缩，表现在价格上也是如此，或者使回
   升态势所能维持的时间变短。在股价弱势反弹的第一或第二天，就需卖出股
   票;这也可能是在股价一落千丈和跌破价格支撑区之前最后一次卖出股票的大
   好机会。 
5. 从顶点处跌落。当某支股票从顶点处跌落8%或更多的话，有时可以检查其之
   前的涨升、顶点处及该次下跌，这有助于判定该股票的涨升是否已经结束，
   或只是一个止常8%至12%的修正。如果由高点下挫超过12%或15%，你则可以考
   虑卖出了。 
6. 相对涨升力量较弱。相对涨升力量变弱也可成为卖出股票的原因之一。当某
   支股票的LSD相对价格力量比率下降至70点以下时，考虑卖出该股票。 
7. 出现“独行侠”。如果某支股票涨升，但若没有同行业其他重要成员的涨升
   作为呼应的话，要考虑卖掉该股票。 

** 跌破价格支撑区域
1. 跌破长期价格涨升线。如果某股价在周末时低于其主要的长期价格涨升线，
   或在维持大量交易额情况下跌破一个关键性的价格支撑区域，就卖掉该股票。
   价格涨升线必须与好几个月内至少是3个日价格或周价格的最低点相连接。过
   短时期内所得到的趋势线没有多大的用处。 
2. 最大的股价日跌幅.如果某支股票在经历了很长一段时期的涨升后，
   然后在某一天内出现自涨升之后最大幅度的日价格下跌，如果同时有其他迹
   象也表明了下跌趋势的话，就可以考虑卖掉股票。 
3. 大额成交量的同时价格下跌。有时，当某股票出现近几年来最大的周成交量
   的同时，价格跌破的话，就卖掉股票。 
4. 200天平均移动线向下转折。经过长期向上涨升之后，如果某股票的200天平
   均移动线开始向下转折，应考虑卖出股票。另外，如果某股票的形态很弱，
   日股价多数处于形态的下半部，而且是在200天移动平均线以下，则应在创新
   高时卖出股票。 
5. 价格在10周移动平均股价之下徘徊不前。经过长期涨升之后，如果某股票的收
   盘价低于其10个星期的平均股价，并且在此水平之下徘徊8-9周，无法反弹，
   那么就需考虑卖出。
** 其他重要的卖出点
1. 如果你将所有的止损标准定为7%到8%,那么当股价上涨25％到30％时，有时就
   可以获利退场。如此赚个3次，就可获得100％甚至更多的收益率。然而，对
   于那些在正确的时点买入、有不错的价格形态、机构投资者也投人资金的市
   场领导股，如果其在1个、2个或3个星期内仅涨升了20％，就不要为了那25%
   或30%的收益率卖掉任何市场领军股。它们有可能会赚大钱.应该继续持有以获得潜
   在更大的利润。

2. 如果遭遇熊市,不要再通过保证金来进行资金,而要保留更多的现金.并且不应
   买入太多股票,如果一定要买,也许你就应该在股价上涨15%时就卖出获利,并
   将止损标准定位3%.

3. 为了成功清仓,大型的机构投资者必须找到下家来买进他们的股票.因此,如果
   某一股票上涨后,利好消息不断并且宣传力度加大的话,你可以考虑将其卖出
   了.
4. 如果某一股票令市场兴奋不已,而且每个人都清楚它会继续上涨的话,赶紧卖
   出,否则可就为时已晚了.当每个人都开始积极幻想，跑来跑去煽动其他入买
   股票时，他们实际上早已把钱都投进去了。现在他们所能做的只是嘴上煽动
   他人。不能进一步将行情往上推升。要推升行情只能靠增加买压来实现。在
   你担心失败和其他人犹豫不决的时候买入股票。然后等到你很开心、面对失
   败泰然自若时卖出股票。
5. 在大多数情况下,当季度收益增长率已经连续两个季度明显下滑(即低于之前
   增长率的2/3)时,应该将股票卖出.
6. 小心不要因为谣言或坏消息而轻易卖出股票;它们通常只能造成短线冲击。谣
   言通常是拿来吓那些个人投资者、小买家的，想让他们将股票出手。 
7. 始终要学会从所有以前的卖出失误中总结经验教训。将过去的买卖点绘在股
   价图上，自己去做分析。认真仔细研究那些失误，制订额外的规则，以避免
   过去所犯的错误进一步造成更大损失。
** 何时应该继续耐心持股
另外，大行情需要一段时间才能完成。不要在涨势的前8周就获利退场，除非股
票出现严重问题，或者因为宣布股票分割，股票连续两三周出现顶点。除非股票
本质不佳或缺乏投资机构及大户的认同，在8周内就可以出现20％涨幅的股票至
少要被持有8周以上。很多情况下，最强劲的股票只需要1至4周的时间就可以上
涨20％或更多，有能力翻一番、两番甚至更多。如果你拥有一支像这样真正的符
合CAN SLIM法则的市场领导股，不妨持有到其第一次下跌，或稍稍低于其10周价
格平均移动线。一旦你赚足了可观的利润，也可在第一次出现短期l0％到20％价
格回整时仍可试着持股。记住，你的目标不是仅仅做对就好，而是在做对的时候
要赚取丰厚的利润。

* 投资者常犯的21个错误
1. 在亏损较小和处理合理范围内的时候，仍固执地持有股票。 ［一旦股票从购
   买价下跌7％－8％就迅速止损］ 
2. 在股价下跌时买进,却越陷越深.
3. 买入时向下摊平而不是向上加码.
4. 不学习如何使用线图,而且不敢买入那些即将在合理的价格形态上创下价格新
   高的股票.
5. 由于既不懂的选股标准,也不知道应该具体关注成功企业的那些方面,所以永
   远都无法在投资领域中入门.
6. 没有指定具体的市场规则来指导自己,因此不知道股价调整何时开始,也不知
   道市场下跌何时会结束以便确定上升趋势.如果想要保护自己的账户不受过多
   的收益返还以及巨额亏损的影响,必须要分辨出市场最高点以及谷底处的重要
   的市场转折点.
7. 不遵循买卖准则,导致错误频出.
8. 将精力完全花在决定买哪些股票上面，而一旦做出投资决策后，却又不知道
   该在何时、何种情况下卖出这些股票。对卖出股票没有任何原则或计划
9. 没有认识到，购买那些得到专业投资机构认可的质量较好的公司股票非常重
   要，以及运用图表分析区证实所选股票和投资时机的正确性也是非常重要的。
10. 偏好买进低价股票.
11. 依据小道消息、传言、情报以及其他信息渠道、顾问公司的建议或者时从电
    视节目上看到的所谓市场专家的意见来做投资选择。
12. 由于红利较高或是市盈率很低,便选择了一些二流的股票.同每股价格增长率
    相比,红利和市盈率的重要性根本就不算什么.
13. 妄图轻轻松松的赚点快钱.没有做好必要的准备,也没有学习一些最为合理的
    投资方法,更没有掌握重要的技巧和原则,这样急功近利只会带来失败.
14. 买入那些令你耳熟能详的大公司股票.
15. 没能识别并采用有益的信息和建议.
16. 急于卖出那些容易获利的股票,对于那些赔钱的股票却死守不放.迅速止损,
    缓慢红利.
17. 过于担心税收和佣金问题.
18. 由于寄希望于通过某种途经一夜致富，而过于依赖期权和期货进行投机。
19. 很少进行市价交易,而是更青睐在买卖委托中设定价格限制.
20. 遇到问题时不能当机立断.
21. 没能客观的看待股票.

* 强势行业孕育超级牛股
行业部门(sector),行业组别(industry group)和亚组别(subgroup).

维亚康姆(Viacom): 行业部门: 休闲娱乐行业; 组别:媒体;亚组别: 广播/电视.

* 投资共同基金成为百万
共同基金投资者最常犯的5个错误:
1. 较少坚持持有10-15年.
2. 担心基金的管理费,周转率或它支付的红利.
3. 本应进行长期投资的时候却被市场上的新闻影响.
4. 在糟糕的市场行情中卖出.
5. 过早的不耐烦,失去信心.



