#+OPTIONS: num:nil H:2 toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:t tags:not-in-toc
#+TITLE: 默克家庭诊疗手册

http://www.msdchina.com.cn/merck-manual/Documents/home/home/index.html

* 药物
** 药物命名
每一专卖药至少有3个名称：化学名称、普通名称(非专卖药)和商品名称(专利或
商标药)。

在美国，药物非专卖名称由官方机构——美国命名委员会(USAN)决定。商品名由制
药公司选择。制药公司总是挑选独特、简短并容易记住的商品名，以便于医师处
方及消费者按名索购。出于这些目的，商品名有时与该药用途有关，如
Diabinese(氯磺丙脲的商品名)用于治疗糖尿病，而Flexeril(三碘季铵酚的商品
名)用于缓解肌痉挛

** 药物与衰老
老年人易患许多慢性疾病，因而用药也较多。每个老年人大约要用4～5种处方药
和2种非处方药。

** 药物的不良反应
据估计美国大约10%的住院病人是为了治疗药物不良反应。15%～30%的住院病人
至少有一种不良反应。虽然许多不良反应是较轻的，当停药或减少剂量时反应消
失，但是另外一些反应是较严重的，并且持续时间很长。

** 新药安全性试验
在美国，新药在由食品和药品管理局(FDA)批准注册以前，必须有严格的动物和
人体试验依据。经多次试验直接评价该药物的有效性(疗效)和相应的安全性。首
先进行动物试验，搜集有关药物动力学(吸收、分布、代谢、排除)、药物动态学
(作用和机制)和安全性的资料，包括可能对生殖能力和后代健康的影响。很多药
物在这一阶段因证明无效或发现毒性太大而被淘汰。

如果动物试验成功，FDA可批准研究者的新药应用研究，然后做人体试验研究。
这种研究要进行几期。在注册前期阶段(1期、2期、3期)，新药首先在少数健康
志愿者身上进行研究，然后加大试验人数，并在打算用该药治疗或预防疾病的病
人或该病严重患者身上试验。此外，还要明确疗效、病灶的类型、不良反应的频
率和对不良反应敏感的因素(如年龄、性别、并发症和与其他药物的相互作用)。

将动物和人体试验资料与药物制造工艺、包装资料、产品标记，以新药申请书形
式呈交FDA。通常，在呈交新药申请后要花2～3年时间进行审查和批准。然而，
对疗效显著的新药FDA可缩短批准时间。

即使在新药批准后，厂商必须实施批准后监测阶段(4期)，及时报告另外或
以前未发现的不良反应。参与用药的医生和药剂师也应跟踪监视。这种监视很重
要，因为即使前期研究发生不良反应每1000份剂量只有1次，在药物上市大量使
用后出现重大不良反应即使是每10000份剂量甚至每50000份剂量中出现1次也是
很大的数字。如果有新的迹象表明新药有相当大的危险，FDA可收回批准。

* 心血管疾病

** 心脏疾病的症状
心脏疾病没有单一的特异症状，只是某些症状能提示心脏病存在的可能性，但当
几种症状同时出现时，常能得出几乎肯定的诊断。

心脏疾病症状包括：某种类型的胸痛、气促、乏力、心悸(常提示心跳减慢、增
快或不规则)、头晕目眩、晕厥等。然而，出现这些症状并非必然存在心脏病。
例如：胸痛可能提示心脏病，但也可发生在呼吸系统疾病和胃肠道疾病。



