#+OPTIONS: num:nil H:2 toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:t tags:not-in-toc
#+TITLE: 默克家庭诊疗手册

http://www.msdchina.com.cn/merck-manual/Documents/home/home/index.html

* 药物
** 药物命名
每一专卖药至少有3个名称：化学名称、普通名称(非专卖药)和商品名称(专利或
商标药)。

在美国，药物非专卖名称由官方机构——美国命名委员会(USAN)决定。商品名由制
药公司选择。制药公司总是挑选独特、简短并容易记住的商品名，以便于医师处
方及消费者按名索购。出于这些目的，商品名有时与该药用途有关，如
Diabinese(氯磺丙脲的商品名)用于治疗糖尿病，而Flexeril(三碘季铵酚的商品
名)用于缓解肌痉挛

** 药物与衰老
老年人易患许多慢性疾病，因而用药也较多。每个老年人大约要用4～5种处方药
和2种非处方药。

** 药物的不良反应
据估计美国大约10%的住院病人是为了治疗药物不良反应。15%～30%的住院病人
至少有一种不良反应。虽然许多不良反应是较轻的，当停药或减少剂量时反应消
失，但是另外一些反应是较严重的，并且持续时间很长。

** 新药安全性试验
在美国，新药在由食品和药品管理局(FDA)批准注册以前，必须有严格的动物和
人体试验依据。经多次试验直接评价该药物的有效性(疗效)和相应的安全性。首
先进行动物试验，搜集有关药物动力学(吸收、分布、代谢、排除)、药物动态学
(作用和机制)和安全性的资料，包括可能对生殖能力和后代健康的影响。很多药
物在这一阶段因证明无效或发现毒性太大而被淘汰。

如果动物试验成功，FDA可批准研究者的新药应用研究，然后做人体试验研究。
这种研究要进行几期。在注册前期阶段(1期、2期、3期)，新药首先在少数健康
志愿者身上进行研究，然后加大试验人数，并在打算用该药治疗或预防疾病的病
人或该病严重患者身上试验。此外，还要明确疗效、病灶的类型、不良反应的频
率和对不良反应敏感的因素(如年龄、性别、并发症和与其他药物的相互作用)。

将动物和人体试验资料与药物制造工艺、包装资料、产品标记，以新药申请书形
式呈交FDA。通常，在呈交新药申请后要花2～3年时间进行审查和批准。然而，
对疗效显著的新药FDA可缩短批准时间。

即使在新药批准后，厂商必须实施批准后监测阶段(4期)，及时报告另外或
以前未发现的不良反应。参与用药的医生和药剂师也应跟踪监视。这种监视很重
要，因为即使前期研究发生不良反应每1000份剂量只有1次，在药物上市大量使
用后出现重大不良反应即使是每10000份剂量甚至每50000份剂量中出现1次也是
很大的数字。如果有新的迹象表明新药有相当大的危险，FDA可收回批准。

* 心血管疾病

** 心脏疾病的症状
心脏疾病没有单一的特异症状，只是某些症状能提示心脏病存在的可能性，但当
几种症状同时出现时，常能得出几乎肯定的诊断。

心脏疾病症状包括：某种类型的胸痛、气促、乏力、心悸(常提示心跳减慢、增
快或不规则)、头晕目眩、晕厥等。然而，出现这些症状并非必然存在心脏病。
例如：胸痛可能提示心脏病，但也可发生在呼吸系统疾病和胃肠道疾病。



* 骨骼、关节和肌肉疾病
** 骨骼、关节和肌肉
人体的骨骼系统是由无数块骨构成。骨是一种不断处于动态变化的人体组织，具
有多种 功能。骨骼为人体提供了力量、稳定性和肌肉运动的支架，也为重要的
内脏器官提供保护。

骨有两种主要的形状：扁平状（如颅骨和椎体）和长管状（如股骨和上肢骨）。
骨的内 在结构基本相同。它坚硬的外壳大部分由蛋白质构成，如胶原以及一种
称为羟磷灰石的物质 ，后者主要由钙和其他一些矿物质构成。羟磷灰石贮存了
机体的大部分钙，是承重骨骼力量 的主要物质基础。骨的中间是软的骨髓，它
的密度比骨低，含有造血细胞。血管穿行在骨中 间而神经则分布在骨的周围。

骨与骨的连接处形成关节。关节的形状决定了运动的幅度和方向。有的关节，如
在颅骨 之间的称之为骨缝，在成年后已不能产生活动，而其他的关节可产生不
同程度的活动，例如 肩关节，称之为杵臼关节，可使上肢产生内收、外旋、向
前、向后以及侧方运动。在肘部、 手指和足趾的绞链式关节仅产生屈曲和伸直
运动。

关节的其他成分为关节提供了稳定性和防止因连续使用造成损伤的保护机制。在
关节内 ，骨的末端是由一层软骨覆盖。软骨是一种光滑的、坚韧的保护性组织，
可吸收震荡，减少关节运动时的摩擦。关节内有滑膜组织包绕关节，形成关节囊。
滑膜组织的细胞可产生清亮 的滑液充满关节腔，这样就降低了关节运动时产生
的摩擦。

肌肉是能产生收缩的束状纤维。骨骼肌是维持肢体姿势和产生运动的组织。在骨
和关节 周围都分布着拮抗性肌群，如在屈肘运动时，在前方的肱二头肌与在后
方的肱三头肌相拮抗 。

肌腱和韧带都是坚韧的结缔组织。肌腱存在于所有附着于骨的肌肉末端，而韧带
则包绕 在关节周围。它们具有稳定和加强关节的作用，使运动按一定方向进行。
滑囊存在于邻近结构之间，如骨与韧带之间，滑囊内充满了滑液，提供缓冲作用，
否则邻近组织在运动时会相 互摩擦，引起磨损和破裂。

组成关节的各部分协调工作，有利于运动的平衡并可预防损伤。当你在行走或跑
步时， 在大腿后方的绳肌收缩，牵动小腿产生屈膝动作；同时，在膝前方的股
四头肌松弛有利于 屈膝；在膝关节内的软骨和滑液可减少运动产生的摩擦；围
绕在膝关节周围的五条韧带维持 了骨的解剖位置；滑囊则在胫骨和髌腱之间提
供了缓冲作用。

** 骨质疏松症
骨质疏松症是指骨密度进行性下降，从而使骨变得脆弱，容易骨折。

骨含有使之坚硬和致密 的矿物质如钙和磷等。为了维持骨密度，机体不仅需要
补充足够的钙和其他矿物质，而且在 体内还应有适当数量的激素，包括甲状旁
腺素、生长激素、降钙素、女性的雌激素和男性的 睾丸酮等。充足的维生素D补
充能促进食物中钙的吸收以及钙与骨的结合。人在30岁以前骨 密度是进行性地
增加并在30岁左右达到最高峰，30岁以后骨密度开始缓慢下降。如果机体调 节
骨矿物质含量的能力失调，那么骨将逐渐变得疏松、脆弱，从而导致骨质疏松症。

** 关节和结缔组织疾病
累及关节、肌肉、骨、软骨和肌腱的疾病被称为结缔组织疾病，因为上述结构包
含了大 量的结缔组织。然而，许多结缔组织疾病实际上又是一类自身免疫性疾
病，因为这类疾病涉 及免疫反应，即结缔组织激发了免疫系统来对抗自身组织
并产生异常抗体附着在这些组织上 （自身性抗体）

** 痛风和假性痛风
痛风是一种突然发作且极易复发并伴有剧烈疼痛的关节炎性疾病，因血中尿酸含
量过高（高尿酸血症）而导致单钠尿酸盐结晶沉积在关节内。

　　关节炎症常可转为慢性，且在本病反复发作后出现关节畸形。约20％的痛风
患者有肾结石。在正常情况下，尿酸是细胞新陈代射的副产品，食物中因含有尿
酸的前体物质，所以尿酸会出现在正常人的血中。当肾脏发生病变或某些药物妨
碍了肾脏清除尿酸的能力，以及因酶异常的遗传性疾病或血癌等疾病使细胞复制
和破坏速度加快，造成血中尿酸水平异常增高，从而导致痛风。


